cloud:
  aws:
    credentials:
      access-key: DO004ENF2GNFYZBZ3PJ9
      secret-key: wmd4JckRA4uqOP7NHeq7em/x+3ClJelPz7pdWyBs3ig
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: mahika-storage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB